image: archlinux
packages:
  - make
  - cmake
  - mkrom
  - patchrom
  - genkfs
  - mktiupgrade
  - valgrind
sources:
  - https://github.com/knightos/scas
  - https://github.com/knightos/kernel
environment:
  project: scas
tasks:
  - build: |
      cd ${project}
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Release ..
      make
      cd ../../kernel
      # Temporary: use scas PR
      git checkout scas
      mkdir bin/TI84pSE -p
      valgrind -s --track-origins=yes --leak-check=full --error-exitcode=1 ../scas/build/scas  --define TI84pSE --include "include/;bin/TI84pSE/;src/00/" --symbols bin/TI84pSE/00.sym --listing bin/TI84pSE/00.list src/00/base.asm -o bin/TI84pSE/00.bin -vv
      if [[ "$(grep ERROR\ SUMMARY log | cut -d\  -f4)" != "0" ]] ; then echo Memory error ; exit 1 ; fi
